import Cookies from '@/components/layout/Cookies'
import './globals.css'
import { Anton, Antonio, Inter, Staatliches } from "next/font/google"
import { SessionProvider } from 'next-auth/react'
import classNames from 'classnames'

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-inter"
})
const antonio = Antonio({
  subsets: ['latin'],
  display: 'swap',
  variable: "--font-antonio"
})

export const metadata = {
  title: 'Aktuelt Studio',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <SessionProvider>
      <html lang="en" className={classNames(inter.className, antonio.variable)}>
        <body>{children}</body>
        <Cookies policyId={"0.0.1"} />
      </html>
    </SessionProvider>
  )
}
